import React from 'react';
import "./globals.css";
import Head from 'next/head';
import { Inter } from "next/font/google";
import { cn } from "./lib/utils";
import Navbar from "../components/navbar";
import providers from "../components/providers";
import { Toaster } from '../../@/components/ui/toaster';
import { Provider } from '@radix-ui/react-toast';
import Providers from '../components/providers';
import'react-loading-skeleton/dist/skeleton.css';

import "simplebar-react/dist/simplebar.min.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <Head>
        <html lang="en" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <Providers>
        <div className={cn(
          'min-h-screen font-sans antialiased grainy',
          inter.className
        )}>
          <Toaster/>
          <Navbar/>
          {children}
        </div>
        </Providers>
    </div>
  );
}

export default RootLayout;
